version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    ports:
      - 6603:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
